'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Layers,Users,Check, Award} from 'lucide-react';
import s from './journey.module.css';
export default function LearningJourney({locale}:{locale:string}) {
 const ref=useRef<HTMLDivElement>(null);
 const [progress,setProgress]=useState(0);
 useEffect(()=>{let frame=0;const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{frame=0;if(!ref.current)return;const rect=ref.current.getBoundingClientRect();setProgress(media.matches?1:Math.max(0,Math.min(1,(innerHeight*.85-rect.top)/(innerHeight*.65))));};const schedule=()=>{if(!frame)frame=requestAnimationFrame(update);};schedule();addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);media.addEventListener('change',schedule);return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',schedule);removeEventListener('resize',schedule);media.removeEventListener('change',schedule);};},[]);
 const labels=locale==='en'?['Learning materials','Create → Learning path','Add courses and stages','Assign to employees','Basics','Advanced topics','Final assessment','Result and certificate']:locale==='kz'?['Оқу материалдары','Құру → Оқу траекториясы','Курстар мен кезеңдерді қосу','Қызметкерлерге тағайындау','Негізгі білім','Күрделі тақырыптар','Қорытынды тексеру','Нәтиже және сертификат']:['Учебные материалы','Создать → Траектория обучения','Добавьте курсы и этапы','Назначьте сотрудникам','Базовые знания','Сложные темы','Итоговая проверка','Результат и сертификат'];
 return <div ref={ref} className={s.diagram} aria-label={labels.join('. ')}><div className={s.top}><BookOpen size={20}/><span>{labels[0]}</span><i/><i/><i/></div><div className={s.create}><Layers size={19}/>{labels[1]}</div><div className={s.setup}><span>{labels[2]}</span><span><Users size={16}/>{labels[3]}</span></div><div className={s.route}><div className={s.line}><span style={{transform:`scaleY(${progress})`}}/></div>{labels.slice(4).map((label,i)=><div className={s.step} key={label} style={{opacity:progress>i/5?1:.4,transform:`translateY(${Math.max(0,(i/4-progress)*18)}px)`}}><span className={progress>(i+1)/5?s.done:s.circle}>{progress>(i+1)/5?<Check size={18}/>:i+1}</span><div><small>0{i+1}</small><h4>{label}</h4></div>{i===3&&<Award size={28}/>}</div>)}</div><div className={s.progress}><span>{locale==='en'?'Learning progress':locale==='kz'?'Оқу үлгерімі':'Прогресс прохождения'}</span><b>{Math.round(progress*100)}%</b><div><i style={{transform:`scaleX(${progress})`}}/></div></div></div>;
}
