import { HeroVideo, LearningScenes, TeamProgress, CourseRibbon } from './UniversityScenes';
import { setRequestLocale } from 'next-intl/server';
import { ArrowUpRight,  Search, Trophy, Palette, Languages, Plug, MonitorPlay, ChartNoAxesCombined, CalendarDays, ScanLine, Award } from 'lucide-react';
import Button from '../../components/Button';
import { pick } from '../../lib/locale';
import s from './university.module.css';
import UniversityMotion from './UniversityMotion';
import LearningJourney from './LearningJourney';
import UniversityHeader from './UniversityHeader';
import Footer from '../../components/Footer';

const copy = {
  ru: {
    label: 'Цифровая платформа для вашей команды', nav: ['Возможности', 'Траектория обучения', 'Экосистема'], cta: 'Запросить демо',
    title: 'Развивайте людей.\nУсиливайте производство.', sub: 'Обучение, которое работает вместе с вашей командой. На объекте, в офисе и в любой точке мира.',
    card: 'Вся команда.\nОдна платформа.', cardSub: 'От первого инструктажа до развития компетенций', scroll: 'Откройте возможности',
    introLabel: 'Обучение с результатом', intro: 'Знания становятся навыками.\nНавыки — культурой безопасности.', introSub: 'Horizon University объединяет обучение сотрудников и управление развитием в одной системе. Меньше организационной работы — больше внимания людям и безопасности.',
    features: [
      ['Обучение без отрыва от производства', 'Курсы, тесты и лонгриды доступны с любого устройства. Сотрудник на объекте в Атырау или Аксае проходит инструктаж в удобное время — без поездки в учебный центр.', 'На объекте · В офисе · В пути'],
      ['Полный контроль прогресса команды', 'Прогресс по подразделениям, группам и каждому сотруднику, результаты тестов и анализ ответов — перед глазами руководителя. Сертификаты выдаются автоматически: для HSE это доказательство обученности при проверках и аудитах.', 'Прозрачность на каждом уровне'],
      ['Траектории обучения и адаптация новичков', 'Собирайте курсы в последовательные программы. Ведите онбординг и индивидуальные планы развития в той же системе — от первого рабочего дня до новых профессиональных задач.', 'Понятный путь к новым навыкам'],
      ['Очное + онлайн в одном окне', 'Календарь мероприятий, тренеры, площадки и запись через каталог. Международные курсы NEBOSH, IOSH, CompEx и внутренние тренинги планируются и учитываются вместе с e-learning.', 'Единый календарь обучения'],
      ['Компетенции, которые видны в работе', 'Оценка 360°, профили компетенций и листы наблюдения помогают проверять рабочие стандарты прямо на площадке. Обучение замыкается на реальное поведение, а не только на тесты.', 'От знаний — к действию'],
    ],
    routeLabel: 'Развитие шаг за шагом', routeTitle: 'Первый день.\nУверенный старт.', routeSub: 'Единая траектория помогает новичку освоиться, а руководителю — видеть, что сотрудник готов к работе.', steps: ['Вводный инструктаж', 'Охрана труда и промышленная безопасность', 'Идентификация рисков', 'Итоговый тест', 'Сертификат'], routeNote: 'Пример программы адаптации',
    ecosystem: 'Больше возможностей.\nМеньше рутины.', ecoLabel: 'Платформа под вашу компанию', extras: [['Умная база знаний', 'Все инструкции, регламенты и ответы на частые вопросы собраны в одном месте и быстро находятся через поиск по смыслу.'], ['Геймификация', 'Баллы, бейджи и рейтинги делают обучение заметнее, понятнее и помогают поддерживать вовлечённость сотрудников.'], ['Ваш бренд', 'Платформа оформляется в фирменном стиле вашей компании: с логотипом, цветами и привычным для сотрудников интерфейсом.'], ['Мультиязычность', 'Обучение удобно для команд, где сотрудники работают на разных языках.'], ['API-интеграции', 'Связывайте обучение с корпоративными системами: 1С:ЗУП, Битрикс24, Microsoft Teams, Zoom, МТС Линк, Google Meet, Tilda, Outlook Calendar, а также с SSO через SAML 2.0, JWT и OpenID.']],
    endLabel: 'Следующий шаг — за вами', endTitle: 'Новый горизонт\nдля вашей команды.', endSub: 'Покажем, как Horizon University решает задачи обучения именно вашей компании.', endNote: 'Демонстрация платформы · Сценарии для вашего бизнеса',
  },
  en: {
    label: 'A digital learning platform for your team', nav: ['Capabilities', 'Learning journey', 'Ecosystem'], cta: 'Request a demo', title: 'Develop your people.\nStrengthen your operations.', sub: 'Learning that works alongside your team. On site, in the office and anywhere in the world.', card: 'Every team.\nOne platform.', cardSub: 'From induction to competency development', scroll: 'Explore the possibilities', introLabel: 'Learning with an impact', intro: 'Knowledge becomes skill.\nSkill becomes a safety culture.', introSub: 'Horizon University brings employee learning and development together. Less administration, more attention to people and safety.',
    features: [ ['Learning without interrupting operations', 'Courses, tests and long reads are available on any device. Employees in Atyrau or Aksai can complete briefings when convenient, without travelling to a training centre.', 'On site · In the office · On the move'], ['Full visibility of team progress', 'Track departments, groups and individual employees, review test results and analyse answers. Certificates are issued automatically, giving HSE teams evidence of training for inspections and audits.', 'Clarity at every level'], ['Learning paths and onboarding', 'Build courses into structured programmes. Manage onboarding and individual development plans in the same system, from the first day to new professional challenges.', 'A clear path to new skills'], ['In-person + online, together', 'A shared calendar, trainers, venues and catalogue registration. Plan and track NEBOSH, IOSH, CompEx and internal training alongside e-learning.', 'One training calendar'], ['Competence that shows at work', '360° assessments, competency profiles and observation checklists help verify work standards on site. Connect learning to real behaviour, beyond test results.', 'From knowledge to action'] ],
    routeLabel: 'Development, step by step', routeTitle: 'Day one.\nA confident start.', routeSub: 'A shared learning path helps new hires settle in and managers understand their readiness for work.', steps: ['Induction', 'Occupational health and industrial safety', 'Risk identification', 'Final assessment', 'Certificate'], routeNote: 'Example onboarding programme', ecosystem: 'More possibilities.\nLess routine.', ecoLabel: 'Built around your company', extras: [['Smart knowledge base', 'Keep instructions and answers close with intelligent search.'], ['Gamification', 'Rankings and game mechanics keep employees engaged.'], ['Your brand', 'Bring your company’s visual identity to the platform.'], ['Multilingual learning', 'Support teams that speak different languages.'], ['API integrations', 'Connect learning with your other business systems.']], endLabel: 'Take the next step', endTitle: 'A new horizon\nfor your team.', endSub: 'Discover how Horizon University can support your company’s learning needs.', endNote: 'Platform demonstration · Scenarios for your business',
  },
  kz: {
    label: 'Командаңызға арналған цифрлық оқу платформасы', nav: ['Мүмкіндіктер', 'Оқу траекториясы', 'Экожүйе'], cta: 'Демоға өтінім беру', title: 'Адамдарды дамытыңыз.\nӨндірісті күшейтіңіз.', sub: 'Командаңызбен бірге жұмыс істейтін оқыту. Объектіде, кеңседе және әлемнің кез келген жерінде.', card: 'Бүкіл команда.\nБір платформа.', cardSub: 'Алғашқы нұсқамадан құзыреттерді дамытуға дейін', scroll: 'Мүмкіндіктерді ашыңыз', introLabel: 'Нәтижелі оқыту', intro: 'Білім дағдыға айналады.\nДағды — қауіпсіздік мәдениетіне.', introSub: 'Horizon University қызметкерлерді оқыту мен дамытуды бір жүйеге біріктіреді. Ұйымдастыру жұмысы азайып, адамдар мен қауіпсіздікке көбірек көңіл бөлінеді.',
    features: [['Өндірістен қол үзбей оқыту', 'Курстар, тесттер және лонгридтер кез келген құрылғыда қолжетімді. Атыраудағы немесе Ақсайдағы қызметкер оқу орталығына бармай, нұсқамадан ыңғайлы уақытта өтеді.', 'Объектіде · Кеңседе · Жолда'], ['Команданың үлгерімін толық бақылау', 'Басшы бөлімшелер, топтар және әр қызметкердің үлгерімін, тест нәтижелері мен жауаптар талдауын көреді. Сертификаттар автоматты түрде беріледі — тексерулер мен аудиттер үшін оқытудың дәлелі.', 'Әр деңгейдегі ашықтық'], ['Оқу траекториялары және бейімдеу', 'Курстарды жүйелі бағдарламаларға біріктіріңіз. Жаңа қызметкерлерді бейімдеу мен жеке даму жоспарларын бір жүйеде жүргізіңіз.', 'Жаңа дағдыларға нақты жол'], ['Күндізгі + онлайн бір терезеде', 'Іс-шаралар күнтізбесі, тренерлер, алаңдар және каталог арқылы тіркелу. NEBOSH, IOSH, CompEx пен ішкі тренингтерді e-learning-пен бірге жоспарлап, есепке алыңыз.', 'Бірыңғай оқу күнтізбесі'], ['Жұмыста көрінетін құзыреттер', '360° бағалау, құзырет профильдері және бақылау парақтары жұмыс стандарттарын тікелей алаңда тексеруге көмектеседі. Оқыту тестпен ғана шектелмей, нақты мінез-құлықпен байланысады.', 'Білімнен — әрекетке']],
    routeLabel: 'Қадам сайын даму', routeTitle: 'Алғашқы күн.\nСенімді бастама.', routeSub: 'Бірыңғай траектория жаңа қызметкердің бейімделуіне, ал басшыға оның жұмысқа дайындығын көруге көмектеседі.', steps: ['Кіріспе нұсқама', 'Еңбекті қорғау және өнеркәсіптік қауіпсіздік', 'Қауіптерді анықтау', 'Қорытынды тест', 'Сертификат'], routeNote: 'Бейімдеу бағдарламасының мысалы', ecosystem: 'Көбірек мүмкіндік.\nАзырақ күнделікті жұмыс.', ecoLabel: 'Компанияңызға сай платформа', extras: [['Ақылды білім базасы', 'Зияткерлік іздеу арқылы нұсқаулықтар мен жауаптарды табыңыз.'], ['Геймификация', 'Рейтингтер мен ойын тетіктері оқуға қызығушылықты арттырады.'], ['Сіздің брендіңіз', 'Платформаны компанияның фирмалық стилінде безендіру.'], ['Көптілділік', 'Әртүрлі тілде сөйлейтін командаларға арналған оқыту.'], ['API интеграциялары', 'Оқытуды компанияның басқа жүйелерімен байланыстырыңыз.']], endLabel: 'Келесі қадам — сізден', endTitle: 'Командаңыз үшін\nжаңа көкжиек.', endSub: 'Horizon University компанияңыздың оқу міндеттерін қалай шешетінін көрсетеміз.', endNote: 'Платформа демонстрациясы · Бизнесіңізге арналған сценарийлер',
  },
};

export default async function UniversityPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = pick(copy, locale);
  const icons = [MonitorPlay, ChartNoAxesCombined, CalendarDays, ScanLine];
  const extraIcons = [Search, Trophy, Palette, Languages, Plug];
  const cta = <Button className={s.cta}>{t.cta}<span className={s.arrow}><ArrowUpRight size={18} /></span></Button>;
  return <UniversityMotion className={s.page}>
    <UniversityHeader/>
    <section data-hero className={s.hero} aria-labelledby="university-title">
      <HeroVideo className={s.heroImage} />
      <div className={s.heroShade} />
      <div className={s.nav}><span className={s.label}><span className={s.dot}/>{t.label}</span></div>
      <h1 id="university-title" className={s.wordmark}>HORIZON<span>UNIVERSITY</span></h1>
      <div className={s.heroBottom}><div><p className={s.heroSub}>{t.sub}</p><h2>{t.title}</h2>{cta}</div><aside className={s.heroCard}><span className={s.cardIcon}><MonitorPlay size={26}/></span><h3>{t.card}</h3><p>{t.cardSub}</p><div className={s.cardFoot}>HORIZON UNIVERSITY<ArrowUpRight size={18}/></div></aside></div>
      <a href="#capabilities" className={s.scroll}>{t.scroll}<span>↓</span></a>
    </section>

    <CourseRibbon/>
    <section id="capabilities" className={s.section}>
      <div className={s.sectionHead}><p className={s.kicker}>✳ &nbsp; {t.introLabel}</p><div><h2>{t.intro}</h2><p className={s.description}>{t.introSub}</p></div></div>
      <LearningScenes title={t.features[0][0]} description={t.features[0][1]} label={t.features[0][2]} locale={locale}/>
      <TeamProgress title={t.features[1][0]} description={t.features[1][1]} label={t.features[1][2]} locale={locale}/>
    </section>

    <section id="journey" className={s.journey}>
      <div className={s.sectionHead}><p className={s.kicker}>✳ &nbsp; {t.routeLabel}</p><div><h2>{t.routeTitle}</h2><p className={s.description}>{t.routeSub}</p></div></div>
      <div className={s.journeyGrid}><article className={s.journeyCopy}><span className={s.number}>03</span><h3>{t.features[2][0]}</h3>{locale === 'ru' ? <div className={s.journeyDetails}><p>Траектория обучения — это готовый маршрут из курсов и этапов, который помогает провести сотрудника через обучение по шагам. Её используют, когда нужно не просто дать один курс, а выстроить понятный путь: сначала базовые знания, потом более сложные темы, затем итоговая проверка.</p><p>Чтобы создать траекторию, в разделе <strong>Учебные материалы</strong> нажмите <strong>Создать → Траектория обучения</strong>, добавьте курсы и при необходимости разделите их на этапы. После этого назначьте траекторию сотрудникам вручную, по правилам автоматического назначения или через Каталог.</p><p>Такой формат удобен для <strong>онбординга, адаптации новичков и поэтапного обучения</strong>, а руководителю позволяет видеть прогресс и результат прохождения.</p></div> : <p>{t.features[2][1]}</p>}<span className={s.tag}>{t.features[2][2]}<ArrowUpRight size={18}/></span></article><LearningJourney locale={locale}/></div>
    </section>

    <section className={s.section}><div className={s.featureGrid}>{[3, 4].map((index) => {const Icon = icons[index - 1]; return <article key={index} className={`${s.feature} ${s.compactFeature}`}><div className={s.featureTop}><span>0{index + 1}</span><Icon size={25}/></div><div className={s.featureCopy}><p className={s.mini}>{t.features[index][2]}</p><h3>{t.features[index][0]}</h3><p>{t.features[index][1]}</p></div><div className={s.tags}>{(index === 3 ? ['NEBOSH', 'IOSH', 'CompEx', 'e-learning'] : ['360°', 'HSE', 'On-the-job']).map(tag => <span key={tag}>{tag}</span>)}</div></article>;})}</div></section>

    <section className={`${s.section} ${s.customCourses}`}><div><p className={s.kicker}>{pick({ru:'Разработка курсов для вашей компании',en:'Custom course development',kz:'Компанияңызға арналған курстар'},locale)}</p><h2>{pick({ru:'Ваши задачи.\nВаши стандарты.\nВаш курс.',en:'Your challenges.\nYour standards.\nYour course.',kz:'Сіздің міндеттеріңіз.\nСіздің стандарттарыңыз.\nСіздің курсыңыз.'},locale)}</h2></div><div><p>{pick({ru:'Создаём уникальные курсы под требования каждой компании — с учётом её процессов, рабочих задач и внутренних стандартов. Сотрудники получают знания, которые могут применять в своей работе.',en:'We create unique courses tailored to each company’s requirements, processes and internal standards, with knowledge employees can apply at work.',kz:'Әр компанияның талаптарына, жұмыс процестері мен ішкі стандарттарына сай бірегей курстар әзірлейміз.'},locale)}</p><div className={s.instructorNote}><Award size={34}/><div><h3>{pick({ru:'Практический опыт. Международная квалификация.',en:'Practical experience. International qualifications.',kz:'Практикалық тәжірибе. Халықаралық біліктілік.'},locale)}</h3><p>{pick({ru:'Наши инструкторы обладают обширным практическим опытом и глубокими профессиональными знаниями. Все инструкторы имеют международные сертификаты и помогают связать обучение с реальными задачами вашей команды.',en:'Our instructors bring extensive practical experience and deep professional knowledge. All hold international certifications and connect learning with your team’s real tasks.',kz:'Нұсқаушыларымыздың практикалық тәжірибесі мол, кәсіби білімі терең. Барлық нұсқаушылар халықаралық сертификаттарға ие.'},locale)}</p></div></div></div></section>
    <section id="ecosystem" className={`${s.section} ${s.ecosystem}`}><div className={s.sectionHead}><p className={s.kicker}>✳ &nbsp; {t.ecoLabel}</p><h2>{t.ecosystem}</h2></div><div className={s.extras}>{t.extras.map(([title, desc], index) => {const Icon = extraIcons[index]; return <article key={title}><Icon size={23}/><h3>{title}</h3><p>{desc}</p></article>;})}</div></section>
    <section className={s.final}><div><p className={s.kicker}>✳ &nbsp; {t.endLabel}</p><h2>{t.endTitle}</h2><p>{t.endSub}</p>{cta}<small>{t.endNote}</small></div><span className={s.orbit} aria-hidden="true"><ArrowUpRight/></span><div className={s.signature}>HORIZON <span>UNIVERSITY</span></div></section>
    <div id="contact" className={s.mainFooter}><Footer/></div>
  </UniversityMotion>;
}
